### ISSUE TITLE
Design für "Gegenüberstellung von NWKs und Praktikumsplätzen"

### ISSUE THREAD

**Issue by andingerMUC** [it-at-m/Praktikumsplaner#105]
Als örtl. Ausbildungsleitung möchte ich eine kombinierte Übersicht von NWKs und Praktikumsplätzen haben, sodass ich an einem Ort die zuzuordnenden NWKs und die Praktikumsplätze sehen kann.
[Issue #19](https://app.zenhub.com/workspaces/praktikumsplaner-650bff5c552a4616fb4b3a8d/issues/gh/it-at-m/praktikumsplaner/19)

---

**Akzeptanzkriterien aus Ursprungs-Issue zur Info:**

- Die aktiven NWKs sollen in einer Liste im linken Bildschirmteil angeordnet sein
- Die Praktikumsplätze sollen in einer Liste im rechten Bildschirmteil angeordnet sein
- Die Praktikumsplätze sind nach den zugehörigen Abteilungen gruppiert
- Zur Zuweisung sind nur Stellen aus dem letzten Meldezeitraum verfügbar

**Zusätzliche Infos (z.B. aus Refinement):**

Diese Infos sollen zur Praktikumsstelle angezeigt werden in der Übersicht:
- Abteilung
- Studiengang/Ausbildungsrichtung
- Studien-/Ausbildungsjahr
- wenn vorhanden Namentliche Anforderung
- "aktiven": siehe https://app.zenhub.com/workspaces/praktikumsplaner-650bff5c552a4616fb4b3a8d/issues/gh/it-at-m/praktikumsplaner/12
- es wird alphabetisch nach Nachnamen sortiert für die NWK (aber Anzeige Vorname Nachname!) 
- es wird alphabetisch (später numerisch) für die Abteilungen sortiert.
- Die Abteilungen sollen mit der tiefsten Ebene angezeigt werden.

---

**Design-Akzeptanzkriterien:**

- [x] Review des Designs durch Andi
- [x] Feedback aus Review wurde eingebaut
- [x] Link zum gereviewten Design wurde Developern zur Verfügung gestellt

**Comment by TobiasCersowsky** [comment]
https://www.figma.com/file/8nfnnZeFlFYMdiuGA0ZhMQ/Zuweisung?type=design&node-id=75%3A1488&mode=design&t=6h0HTzWeSTlk4rd9-1
