### ISSUE TITLE
NWK Übersicht

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#12]
Ich als örtl. Ausbildungsleitung möchte alle NWKs in einer Übersicht sehen, sodass ich schnell sehen kann welche NWKs ich unterbringen muss.

**Akzeptanzkriterien:**
- [x] Es werden alle aktive NWKs angezeigt

Zusätzliche Infos zur Implementierung:
Diese Infos sollen angezeigt werden:
- Name
- Studiengang
- Jahrgang/Semester

"Aktiv": Bedeutet diese NWK befindet sich weiterhin bei der Stadt in Ausbildung

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Unittest gepflegt
- [x] Dokumentation ist gepflegt
- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by MoonaLiisaa** [comment]
Diese Story wird als Referenzstory gesehen und mit Aufwand 5 geschätzt.

Gründe hierfür sind:
- die Story beinhaltet viele verschiedene Komponenten
- Keine komplexe Logik
- Einfaches Backend
- Nicht aufwendiges Design
- Voraussichtlich wenig notwendige Tests
