### ISSUE TITLE
Punkte aus CodeReview

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Praktikumsplaner#126]
Ich habe mir den Code angesehen und dabei sind folgende Dinge aufgefallen.

# Bugs
## Namentliche Anforderung ist ein Pflichtfeld im Frontend
  - wenn ich durchtabe und es leer lasse kommt die Meldung `Der Name der angeforderte NWK darf nicht länger als 255 Zeichen sein`
  - ![grafik](https://github.com/it-at-m/Praktikumsplaner/assets/13592751/b4c344db-280a-4934-89a5-df9d22dbab2c)

## Keine Fehlermeldung bei Gegenüberstellung
- es kommt keine Fehlermeldung wenn das Backend nicht vorhanden ist

# Optimierung Backend
## Mehr Methoden der Streaming-API verwenden
- anstatt `.collect(Collectors.toList())` versuchen direkt `.toList()` zu verwenden
- Grouping via Stream: `.collect(Collectors.groupingBy())`
## Naming verbessern
- getAllPraktikumsstellen liefert nicht alle sondern die des zuletzt vergangenen Meldezeitraums
  - betrifft sowohl den Controller als auch den Service
- bei `PraktikumsstellenService.getAllPraktiumsstellen` wurde eine TreeMap verwendet damit nach den Keys sortiert wird. Die Sortierung könnte sich auch im Methodennamen wiederfinden damit es leichter nachvollziehbar ist was die Methode macht
- Property hat den Namen `Studienart` der Typ ist `Studiengang`. Vielleicht könnte man das auch angleichen
- Die Property in der Annotation zur Validierung von Studiums-/ Ausbildungsstelle welche das zu prüfende Feld referenziert sollte klarer benannt werden damit man weiß das darin eine Property enthalten sein soll

# Frontend
- Auf einheitliches Naming bei den Dateien achten
  - `gegenueberstellungView.vue` ist als einzige View klein geschrieben
- Mehr Komponenten wieder verwenden
  - es gibt diverse Select-Komponenten die ein ja-nein erlauben
  - die Meldungsseiten haben Komponenten die bei beiden Ansichten gleich sind
- FetchUtils
  - die Subfunction in bgetPostConfig die den Body ermittelt wird im weiteren Sinne auch in der getPutConfig oder getPatchConfig wieder verwendet. Schaut mal nach ob man dieses sinngemäße Wiederverwendung besser im Code abbilden kann
- Verbesserung des Namings der Methode `getAllActiveNWKs` in `ActiveNwkList.vue`: Ein get sollte etwas zurück geben. Diese Methode macht das nicht. Daher sollte der Name angepasst werden. Spontan viele mir `load` ein.

## sonstiges
- MagicString `,` in `DayOfWeekConverter` in Konstante auslagern
- Test zu `GlobalExceptionHandler` ergänzen
- Enum Studiengang enthält auch Ausbildungsrichtungen. Hier wurde die Trennung zwischen Ausbildung und Studium aus meiner Sicht nicht konsequent durchgezogen
- eine `NotNull`-Annotation liefert bei einem `boolean` aus meiner Sicht keinen Mehrwert

---

Falls einige Punkte bereits behoben sind oder aus eurer Sicht doch so passen gerne kommentieren

**Comment by danielnwz** [comment]
1. Bug: "wenn ich durchtabe und es leer lasse kommt die Meldung Der Name der angeforderte NWK darf nicht länger als 255 Zeichen sein" ist bereits gefixt
