### ISSUE TITLE
Praktikumsstellen Meldung örtl. Ausbildungsleitung unabhängig vom Meldezeitraum

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#130]
**User Story:**  
Als örtliche Ausbildungsleitung möchte ich Praktikumsstellen auch außerhalb des Meldezeitraums melden können damit ich nicht gemeldete Stellen die mit mir abgesprochen wurden noch im Nachhinein hinzufügen kann.

**Akzeptanzkriterien:**  
- [x] Es gibt bei der Meldung der Stellen die Möglichkeit einen Meldezeitraum zu auszuwählen.
- [x] Das soll nur für die Ausbildungsleitung verfügbar sein. 
- [x] Die Stelle kann zum Meldezeitraum hinzugefügt werden, unabhängig davon ob dieser aktiv ist. 
- [x] Bei der Auswahl ist der Name und der Zeitraum ersichtlich.

**Zusätzliches Infos zur Implementierung:**

**Frragen für Refinement:**
- [x] Sind Zeitraumname und Daten nur für AL sichtbar oder auch bei der Meldung durch Ausbilder*innen?

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by danielnwz** [comment]
Meldezeitraum für Ausbilder*innen nicht sichtbar

**Comment by Tuckerle** [comment]
- [ ] GetAll-Endpoint Meldezeitraum
- [ ] Sortierung nach geringstem Abstand zu "heute" im Backend
- [ ] Meldezeitraum Auswahlfeld im Frontend einbauen
- [ ] PostEndpoint anpassen, sodass Meldezeitraum mitgegeben werden kann
- [ ] Verbindung mit diesem PostEndpoint
- [ ] Security Restriction (Sichtbar nur für Ausbilderinnen)
