### ISSUE TITLE
Fehlermeldungen für die User

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#132]
**User Story:**  
Als örtliche Ausbildungsleitung und örtliche Ausbilder*in möchte ich bei Fehlern, die während meiner Nutzung der Applikation auftreten, eine aussagekräftige Fehlermeldung erhalten, damit ich weiß wo das Problem liegt.

**Akzeptanzkriterien:**  
- [x] Angezeigte Fehlermeldung enthält die Ursache
- [x] Fehlermeldungen sind auf deutsch formuliert

**Zusätzliches Infos zur Implementierung:**
Bei einem 500 Internal Server Error soll folgende Nachricht oder ähnliches angezeigt werden:
"Interner Fehler! Sollte der Fehler weiterhin auftreten, wenden Sie sich bitte an einen Administrator!"

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by Tuckerle** [comment]
- [ ] Fehlermeldungen im Backend prüfen und ggf. korrigieren/übersetzen
- [ ] Fehlermeldungen im Frontend aus den HTTP-Responses auslesen und an den User weitergeben
- [ ] Fehlermeldung die nicht direkt durch das Backend geschickt werden indentifizieren und wenn möglich aufbereiten

**Comment by danielnwz** [comment]
Dieses Issue wurde auf Grund von zeitlichen Engpässen nicht in einem Usabilty-Test getestet. Zählt für uns jedoch trotzdem als abgeschlossen.
