### ISSUE TITLE
Übersicht Meldezeitraum

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#133]
**User Story:**  
Als örtliche Ausbildungsleitung möchte meine erstellten Meldezeiträume sehen, damit ich im Überblick behalten kann, welche Zeiträume ich bereits erstellt habe. 

**Akzeptanzkriterien:**  
- [x] Alle Meldezeiträume werden in eine Übersicht angezeigt
- [x] Der Meldezeitraum der aktuell aktiv ist, soll besonders markiert werden
- [x] Die Meldezeiträume sind nach Datum sortiert
- [x] Ist kein Zeitraum vorhanden, soll das dem Nutzer angezeigt werden. 
- [x] Die Übersicht ist nur für die AL zu sehen
- [x] vergangene Zeiträume sollen in einer extra Liste angezeigt werden

**Zusätzliches Infos zur Implementierung:**
Idee aus #9 beim Design und Implementierung beachten. 

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by Tuckerle** [comment]
- [ ] GetEndpoint um vergangene Zeiträume erweitern
  - [ ] Sortierung im Backend nach Startdatum nächster zu entferntestem
- [ ] GetEndpoint um Zukünftige Zeiträume erweitern
  - [ ] Sortierung im Backend nach Startdatum nächster zu entferntestem
- [ ]  Verbindung Frontend zu Backend
- [ ] Design Vorhanden
- [ ] Design Implementieren
- [ ] Security Restrictions (sichtbar nur für AL)
