### ISSUE TITLE
Warnungen in der Zuweisung

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#137]
**User Story:**  
Als örtliche Ausbildungsleitung möchte ich Warnungen erhalten falls Unstimmigkeiten bei der Zuweisung entstanden sind, damit ich die Anforderungen der gemeldeten Praktikumsstellen richtig erfülle.  

**Akzeptanzkriterien:**  
- [x] Die Warnungen werden beim Versuch der Durchführung der Aktion angezeigt.
- [x] Es wird eine Warnung angezeigt, wenn Praktikumsplätze, mit Dringlichkeit Zwingend und Dringend, nicht mit einer NWK besetzt sind
- [x] Es wird eine Warnung angezeigt, wenn Praktikumsplätze, mit namentlicher Anforderung unbesetzt sind
- [x] Es wird eine Warnung angezeigt, wenn NWKs noch nicht einem Praktikumsplatz zugewiesen sind
- [x] Die Aktion soll erst dann durchgeführt werden, wenn alle Warnungen bestätigt worden sind.

**Zusätzliches Infos zur Implementierung:**
- Bei folgenden Aktionen sollen die Warnungen aktuell erscheinen: Export der Zuweisungstabelle, Mail-Versand erfolgreiche Zuteilung
- Es soll für jede NWK eine eigene Warnung erscheinen
- Jede Warnung soll einzeln angezeigt werden
---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by Tuckerle** [comment]
- [ ] Komponentenarchitektur entwickeln
  - [ ] Übergabe einer Menge an warnungen
  - [ ] Warnungen der Reihe nach anzeigen
  - [ ] Ergebnisse der warnungen Protokollieren
  - [ ] Ablehnen oder Akzeptieren abhängig von den Ergebnissen
    - [ ] Eine Ablehnung führt zu sofortiger Gesamtablehnung
    - [ ] Alle Akzeptieren führt zu Gesamtakzeptanz
- [ ] Warnung als Type anlegen
- [ ] Komponente vor Export und Mailversand einbauen (wenn vorhanden) und mit Warnungen füttern
