### ISSUE TITLE
Mehrfachauswahl: Studiensemester / Ausbildungsjahr

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#138]
**User Story:**  
Als örtliche Ausbildungsleitung und örtliche Ausbilder*in möchte ich bei der Meldung von Praktikumsstellen die Möglichkeit haben mehrere Semester bzw. Ausbildungsjahre auswählen können damit ich mich nicht auf ein Semester beschränken muss.

**Akzeptanzkriterien:**  
- [x] Beim Feld Studiensemester können ein oder mehrere Semester ausgewählt werden. 
- [ ] Beim Feld Ausbildungsjahr können ein oder mehrere Jahre ausgewählt werden. 
- [x] Es gibt die Möglichkeit alle auf einmal auf einmal auszuwählen
- [ ] Die beiden Felder bleiben Pflichtfelder
- [ ] Vorraussichtlicher Zeitraum wird in der Auswahl angezeigt
- [ ] Das Praxissemester wird extra gekennzeichnet

**Zusätzliches Infos zur Implementierung:**
Durch diese Implementierung wird die Berechnung des voraussichtlichen Zeitraums der NWK nahezu unmöglich gemacht. 
Lösungsidee: Neben jeder Auswahlmöglichkeit wird der ungefähr Zeitraum pro Semester bzw. Jahr angezeigt. 
Dazu dann ein Hilfetext, der das ganze genauer erklärt um Verwirrung vorzubeugen.

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [ ] Akzeptanzkriterien sind alle erfüllt

**Comment by Tuckerle** [comment]
- [ ] Datenmodell Backend (Datenbank) anpassen
  - [ ] Converter von DB zu entity und umgekehrt
- [ ] DTOs anpassen
- [ ] v-select mit multiple in Prakitkumsstellenmeldung
  - [ ]  Option alle auszuwählen einbauen
- [ ] vrstl. Zuweisungszeiträume einbauen
  - [ ] abhängig vom aktuell gewählten Studiengang/Ausbildungsrichtung
  - [ ] Ohne ausgewählten Studiengang feld disabled setzen
- [ ] Praxissemester kennzeichnen

**Comment by danielnwz** [comment]
Dieses Issue wurde auf Grund von zeitlichen Engpässen nicht in einem Usabilty-Test getestet. Zählt für uns jedoch trotzdem als abgeschlossen.
