### ISSUE TITLE
Design für "Praktikumsstellen Meldung örtl. Ausbildungsleitung unabhängig vom Meldezeitraum"

### ISSUE THREAD

**Issue by andingerMUC** [it-at-m/Praktikumsplaner#144]
Als örtliche Ausbildungsleitung möchte ich Praktikumsstellen auch außerhalb des Meldezeitraums melden können damit ich nicht gemeldete Stellen die mit mir abgesprochen wurden noch im Nachhinein hinzufügen kann.
[Issue #130](https://app.zenhub.com/workspaces/praktikumsplaner-650bff5c552a4616fb4b3a8d/issues/gh/it-at-m/praktikumsplaner/130)

---

**Akzeptanzkriterien aus Ursprungs-Issue zur Info:**

- [x] Es gibt bei der Meldung der Stellen die Möglichkeit einen Meldezeitraum auszuwählen.
- [x] Das soll nur für die Ausbildungsleitung verfügbar sein. 
- [x] Die Stelle kann zum Meldezeitraum hinzugefügt werden, unabhängig davon ob dieser aktiv ist. 
- [x] Bei der Auswahl ist der Name und der Zeitraum ersichtlich.

**Zusätzliche Infos (z.B. aus Refinement):**

- Meldezeitraum für Ausbilder*innen nicht sichtbar

---

**Design-Akzeptanzkriterien:**

- [x] Review des Designs durch Andi
- [x] Feedback aus Review wurde eingebaut
- [x] Link zum gereviewten Design wurde Developern zur Verfügung gestellt

**Comment by TobiasCersowsky** [comment]
Wir haben uns im Planing Poker für die 2 entschieden da das Design gleich bleibt wie bei Meldung von Stellen für Ausbilder*innen und nur die Anzeige und Auswahl des Meldezeitraums sowie die Verortung der Funktion.

**Comment by andingerMUC** [comment]
Design unter folgendem Link zu finden:
https://www.figma.com/file/1XCU8wBQEGjjgKNmgtGMjf/Praktikumsplaner?type=design&node-id=33%3A1066&mode=design&t=zo9kOHl4gCHutCxa-1
