### ISSUE TITLE
Design für "Details zu NWKs bei Zuweisung"

### ISSUE THREAD

**Issue by andingerMUC** [it-at-m/Praktikumsplaner#146]
Als örtl. Ausbildungsleitung möchte ich auf der Zuweisungsseite schnell alle vorhandenen Informationen zu einer NWK erhalten können, sodass ich diese bei der Zuweisung berücksichtigen kann.
[Issue #20](https://app.zenhub.com/workspaces/praktikumsplaner-650bff5c552a4616fb4b3a8d/issues/gh/it-at-m/praktikumsplaner/20)

---

**Akzeptanzkriterien aus Ursprungs-Issue zur Info:**

- [x] Die Informationen einer NWK werden angezeigt
- [x] Die Zuweisungsseite muss dafür nicht verlassen werden

**Zusätzliche Infos (z.B. aus Refinement):**

- Welche Informationen sind das? Vorlesungstage, falls möglich Hinweis auf Berufsschulblöcke, Personalnummer (Herkunft bisher unbekannt; wird zukünftig wichtig), Mailadresse;

---

**Design-Akzeptanzkriterien:**

- [x] Review des Designs durch Andi
- [x] Feedback aus Review wurde eingebaut
- [x] Link zum gereviewten Design wurde Developern zur Verfügung gestellt

**Comment by andingerMUC** [comment]
Planing Poker:
haben uns für 1 entschieden, da bereits ein Design vorhanden ist, das die Entwickler auch bereits gesehen und für machbar erklärt haben

**Comment by TobiasCersowsky** [comment]
https://www.figma.com/file/8nfnnZeFlFYMdiuGA0ZhMQ/Zuweisung?type=design&node-id=75%3A1488&mode=design&t=6h0HTzWeSTlk4rd9-1
