### ISSUE TITLE
Design für "Mail-Versand: erfolgreiche Praktikumszuteilung Ausbilder*innen"

### ISSUE THREAD

**Issue by andingerMUC** [it-at-m/Praktikumsplaner#147]
Ich als örtl. Ausbildungsleitung möchte die Info-Mails an die örtl. Ausbilder*innen automatisiert verschicken lassen, sodass ich nicht > 100 Mails selbstständig verschicken muss.
[Issue #24](https://app.zenhub.com/workspaces/praktikumsplaner-650bff5c552a4616fb4b3a8d/issues/gh/it-at-m/praktikumsplaner/24)

---

**Akzeptanzkriterien aus Ursprungs-Issue zur Info:**

- [x] Es wird der genaue Zuweisungszeitraum der jeweiligen Studiengruppen abgefragt
- [ ] Mail-Vorlage wird mit korrekten Daten befüllt
- [x] Mail wird nach Bestätigung durch mich versendet
- [x] ein Feedback wird zurückgegeben ob die Mails erfolgreich versendet wurden

**Zusätzliche Infos (z.B. aus Refinement):**

- Aufbau des Mail wird noch geklärt

---

**Design-Akzeptanzkriterien:**

- [ ] Review des Designs durch Andi
- [ ] Feedback aus Review wurde eingebaut
- [ ] Link zum gereviewten Design wurde Developern zur Verfügung gestellt

**Comment by danielnwz** [comment]
Issue wurde auf 'Blocked' gesetzt, da wir davon ausgehen, dass es schon bearbeitet wurde, aber die Dokumenation der Ergebnisse aktuell noch fehlt.
