### ISSUE TITLE
Design für "Export der Zuweisungstabelle"

### ISSUE THREAD

**Issue by andingerMUC** [it-at-m/Praktikumsplaner#148]
Ich als örtl. Ausbildungsleitung möchte die Zuteilungen in Form einer Tabelle exportieren können, sodass ich diese Tabelle dann ans POR übermitteln kann.
[Issue #22](https://app.zenhub.com/workspaces/praktikumsplaner-650bff5c552a4616fb4b3a8d/issues/gh/it-at-m/praktikumsplaner/22)

---

**Akzeptanzkriterien aus Ursprungs-Issue zur Info:**

- [ ] Zuweisungen werden in eine Tabelle exportiert
- [ ] Tabelle wird automatisch auf das Endgerät geladen

**Zusätzliche Infos (z.B. aus Refinement):**

- Es soll für jede NWK eine eigene Warnung erscheinen
- Kategorie ist nicht notwendig, da es keine Liste für alle NWK geben soll
- Die Warnung soll erst bestätigt werden und erst dann der Export durchgeführt
- Infos zur Form der Exportierten Exceltabelle:
- Die Form sollte ähnlich zu der Zuweisungstabelle sein die PO jetzt händisch in Excel eintragen und ans POR schicken da das POR dort alle Rückmeldungen auch aus anderen Referanten noch einträgt. Zusätzlich Spalte namentliche Anforderungen ist natürlich kein Problem (siehe Issue #22)

---

**Design-Akzeptanzkriterien:**

- [ ] Review des Designs durch Andi
- [ ] Feedback aus Review wurde eingebaut
- [ ] Link zum gereviewten Design wurde Developern zur Verfügung gestellt

**Comment by andingerMUC** [comment]
Planing Poker:
haben uns auf 1 geeinigt, da es sich unserem Verständnis nach nur um einen Export-Button handelt

To Do:
mit Entwicklern klären, was es mit den Warnungen auf sich hat. Sind die nur nicht mehr aus der Story genommen worden?

**Comment by danielnwz** [comment]
Issue wurde auf 'Blocked' gesetzt, da wir davon ausgehen, dass es schon bearbeitet wurde, aber die Dokumenation der Ergebnisse aktuell noch fehlt.
