### ISSUE TITLE
Zuweisung von NWKs zu Praktikumsplätzen

### ISSUE THREAD

**Issue by LuisEinig** [it-at-m/Praktikumsplaner#15]
Ich als örtl. Ausbildungsleitung möchte NWKs zu Praktikumsplätzen zuweisen können, sodass ich meiner Aufgabe als örtl. Ausbildungsleitung möglichst einfach/effizient nachgehen kann.

**Akzeptanzkriterien:**
- [x] NWK kann zu einem Praktikumsplatz zugewiesen werden
- [x] Die zugewiesene NWK wird im Praktikumsplatz angezeigt
- [x] Die Zuweisung wird dauerhaft gespeichert
- [x] ein Feedback wird zurückgegeben ob die NWK Zugewiesen wurde
- [x] Ein besetzter Praktikumsplatz wird entsprechend markiert und gesperrt
- [x] Die NWK wird nach der Zuteilung aus der NWK-Zuteilungs-Liste entfernt
- [x] Es wird eine Warnung angezeigt, wenn eine NWK auf eine unpassende Stelle zugewiesen werden soll

Zusätzliche Infos zur Implementierung:

Fragen für Refinement:
- [x] was ist eine unpassende Stelle
  - [x] Bei welchen Kriterien soll geprüft werden ob sie passen und wie
    - [x] Semster/Ausbildungsjahr wird von Ausbildern als Minimum angegeben, sollen wir das auch so behandeln?
  - [x] Soll auch der Grund weshalb die NWk unpassend ist angezeigt werden
- [x] Soll es wirklich nur eine Warnung sein aber die Zuweisung trotzdem durchgeführt werden, oder soll es eine Art bestätitgungsdialog sein
("NWK passt nicht zur Stelle (Studiengang unpassend), trotzdem zuweisen? [Ja] [Nein]")

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Unittest gepflegt
- [x] Dokumentation ist gepflegt
- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by andingerMUC** [comment]
Refinement:
was ist eine unpassende Stelle: Azubis nicht auf Studentenstellen und andersrum --> es soll ein Hinweis erscheinen, aber grundsätzlich soll es möglich sein solche Zuweisungen trotzdem durchzuführen (Ausnahmefall)
    Bei welchen Kriterien soll geprüft werden ob sie passen und wie: Studium/Azubi, Studien- oder Ausbildungsrichtungen, Ausbildungsjahr/Semester, namentliche Zuweisung (wenn vorhanden)
        Semster/Ausbildungsjahr wird von Ausbildern als Minimum angegeben, sollen wir das auch so behandeln? Lösung durch Mehrfachauswahl siehe Issue #8
    Soll auch der Grund weshalb die NWk unpassend ist angezeigt werden? Ja bitte

Soll es wirklich nur eine Warnung sein aber die Zuweisung trotzdem durchgeführt werden, oder soll es eine Art bestätitgungsdialog sein? ("NWK passt nicht zur Stelle (Studiengang unpassend), trotzdem zuweisen? [Ja] [Nein]")
--> Es soll explizit bestätigt werden durch die Leitung

**Comment by Tuckerle** [comment]
- [ ] Backend Update Endpoint für Praktikumsstellen
- [ ] Datenstruktur anpassen (Datenbank)
- [ ] Validierung der Zuweisung (Backend) (z.B. Keine Doppelbelegung)
- [ ] Service erweitern um Zuweisung zu speichern
- [ ] Design vorhanden
- [ ] Design im Frontend implementieren
  - [ ] Frontend Validierung
  - [ ] Warnungsdialoge
- [ ] Frontend Verbindung zu Backend
