### ISSUE TITLE
NWK anlegen Formular

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#16]
Ich als örtl. Ausbildungsleitung möchte NWKs per Formular Anlegen können, sodass ich NWKs welche beim Import der Excel Datei noch nicht bekannt waren schnell ergänzen kann.

**Akzeptanzkriterien:**
- [x] Formular fragt Daten ab die in normalerweise in der Excel Datei stehen
- [x] ein Feedback wird zurückgegeben ob die NWK Angelegt wurde

Zusätzliche Infos zur Implementierung:
Angaben: 
- Vorname
- Name
- Studiengang/Ausbildungsrichtung
- Jahrgang
- Vorlesungstage

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Unittest gepflegt
- [ ] Dokumentation ist gepflegt
- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by IamPekka058** [comment]
- [ ] Backendenpoint anlegen
- [ ] Frontendservice implementieren
- [ ] Dialog anlegen

**Comment by danielnwz** [comment]
Dieses Issue wurde auf Grund von zeitlichen Engpässen nicht in einem Usabilty-Test getestet. Zählt für uns jedoch trotzdem als abgeschlossen.
