### ISSUE TITLE
Ausbildungspraktikumsstelle Programmierkenntnisse no line break in assignment

### ISSUE THREAD

**Issue by LuisEinig** [it-at-m/Praktikumsplaner#162]
**Describe the bug**
When Programmierkenntnisse of a FISI is not given. On the assignment page when opening the details of a Praktikumsstelle, a line break is missing. Result is seen below in the screenshot

**To Reproduce**
1. Go to 'Zuweisung'
2. Click on the arrow of a Praktikumsstelle
3. See error

**Expected behavior**
Projektarbeit should be in the next line.

**Screenshots**
![grafik](https://github.com/it-at-m/Praktikumsplaner/assets/69314043/b9202c3d-fbbb-488c-96b4-b970bac290c8)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox
 - Version 102.15.1esr

**Additional context**

**Comment by danielnwz** [comment]
Issue wurde nicht abgenommen, da der Fehler noch nicht behoben wurde.

**Comment by danielnwz** [comment]
In der Datenbank stand "" statt null, weshalb die Aneige da war. Noch ist unklar, wieso "" in der Datenbank stand.
