### ISSUE TITLE
Misleading/False Warning message when assigning Auszubildende to Studierendenstelle

### ISSUE THREAD

**Issue by Tuckerle** [it-at-m/Praktikumsplaner#166]
**Describe the bug**
When trying to assign a Ausbzubildende to a Praktikumsstelle designed for a Studierende, then a warning with a kind of weird message is shown.

**To Reproduce**
Prereqs: You need at least one Praktikumsstelle to assign NWK to, which is designed for a Studierende and a NWK which is a Auszubildende.

1. Go to 'Zuweisung'
2. Drag the NWK (Auszubildende) onto the Praktikumsstelle (for a Studierende)
3. The Warning Dialog should be shown, read the last message and see the error

**Expected behavior**
No message regarding the semester should be displayed when the NWK has no semester, as it is a Auszubildende.

**Screenshots**
<img width="798" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTJVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--892b448f9c0070075ff3b81fe089055524e8a8b4/grafik.png" alt="grafik.png" />

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 102.15.1esr (64-Bit)

**Comment by LuisEinig** [comment]
Bug was reintroduced in recent PRs due to negligence
