### ISSUE TITLE
Sortierte Meldezeiträume in der Erstellung der Praktikumsstellen

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#176]
**User Story:**  
Als örtl. Ausbildungsleitung möchte ich die Meldezeiträume bei der Erstellung von Praktikumsstellen in einer sortierten Reihenfolge sehen, damit ich schneller den gesuchten Zeitraum finde. 

**Akzeptanzkriterien:**  
- [x] Meldezeiträume werden `sortiert` angezeigt

**Zusätzliches Infos zur Implementierung:**
Aktuellster Meldezeitraum oben
dann alle zukünftigen
dann die vegangenen
die einzelnen Gruppen sind so sortiert, dass der nähste zum aktuellen Zeitraum oben ist

Fragen fürs Refinement:
- welche Sortierung ist gewünscht? bsp. aktueller ganz oben, nach datum abstigend

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by Tuckerle** [comment]
- [ ] Evaluieren ob Backend oder Frontendseitig sortiert werden soll
- [ ] ggf. Daten verschiedener Endpunkte in eine Liste zusammenführen

**Comment by LuisEinig** [comment]
Da schon die Daten in der richtigen Reihenfolge an das Frontend gesendet werden z.b. beim Meldezeitraum. Habe ich entschieden, es im Frontend zusammen zu setzen.
