### ISSUE TITLE
Zuweisung von anderen Objekten frontendseitig möglich

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#177]
**Describe the bug**
Es ist möglich verschiendeste HTML-Objekte, wie z.B.: die Links im Navigation-Drawer auf die Praktikumsstellen zuzuweisen. Dem User wird eine erfolgreiche Zuweisung als Antwort zurückgegeben. 
Wenn man diese Zuweisung wieder entfernt, dann wird eine NWK ohne vorhande Daten in die Liste der NWKs eingefügt. 
Nach dem Reloaden der Seite ist das Objekt wieder weg. 

**To Reproduce**
1. Gehe zu 'Zuweisung'
2. Öffene den Navigation-Drawer
3. Ziehe ein Element aus dem Navigation-Drawer
4. Drope es auf eine Praktikumsstelle ohne zugewiesene NWK
5. Eine "leere NWK" wurde erfolgreich der Praktikumssstelle zugewiesen
6. Siehe den ersten Fehler
7. Entferne die Zuweisung
8. Sieh, dass ein Element der NWK-Liste zugewiesen wurde.
9. Siehe den weiteren Fehler

**Expected behavior**
Es sollte nicht möglich sein etwas Anderes als eine NWK auf eine Praktikumsstelle zuweisen zu können. 

**Screenshots**
<img width="863" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE95QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--956f7072f9b3cf79ee485ce0c7c5668fded74eb0/grafik.png" alt="grafik.png" />
<img width="624" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFN5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a936fd12b695a4678f7c979c769d9cc7a56e9d0d/grafik.png" alt="grafik.png" />

**Comment by Tuckerle** [comment]
- [ ] Nwk Store aus Drag-n-Drop Lösung eliminieren
- [ ] DragEvent für DnD Datenübermittlung nutzen
- [ ] filter in drop function, um nur korrekte daten durchzulassen
