### ISSUE TITLE
Info zur Erklärung von Planstellen

### ISSUE THREAD

**Issue by TobiasCersowsky** [it-at-m/Praktikumsplaner#187]
- da Planstellen nicht jedem etwas sagen soll neben der Planstellen Auswahl (JA/NEIN) noch ein info text sein der die funktion einer Planstelle erklärt

**Comment by danielnwz** [comment]
Issue wurde auf 'Blocked' gesetzt, da wir davon ausgehen, dass es schon bearbeitet wurde, aber die Dokumenation der Ergebnisse aktuell noch fehlt.
