### ISSUE TITLE
NWK-Details Button, wenn keine Details vorhanden sind

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#192]
**Describe the bug**
Wenn eine NWK keine details hat wird aktuell trotzdem der Button zum ausklappen der details angezeigt. Wenn dieser geklickt wird, wird die Box mit der NWK etwas größer aber kein neuer Inhalt angezeigt.

**To Reproduce**
1. Go to Zuweisung
2. Click on the details Button of a NWK
4. Box opens without additional information

**Expected behavior**
The button should not be visible and the box should not expand without information.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tuckerle** [comment]
- [ ] function zum prüfen auf ob Details zu einer NWK vorhanden sind implementieren (basierend auf Detail Text oder aber direkt bestimmte Details prüfen)
- [ ] Pfeil zum ausklappen von details nur zeigen wenn Details vorhanden sind
- [ ]
