### ISSUE TITLE
Zeilenumbruch des NWK-Namens in der Zuweisung-Liste ist zu früh

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#193]
**Describe the bug**
Wenn NWK Namen zu lang sind, dann brechen diese ungefähr in der Mitte der Card / Liste um, obwohl noch genügend Platz wäre um diese teilweise ganz auszuschreiben. 

**To Reproduce**
1. Go to 'NWK'
2. Upload Nwks with longer name
3. Go to 'Zuweisung'

**Expected behavior**
Namen der Nwks sollten erst in eine neue Zeile umbrechen, wenn sie das rechte Ende der Liste bzw. Card erreichen. 

**Screenshots**
<img width="730" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU82QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a69e9939e7ad489e3bd502ee6c9053d0aa82211f/grafik.png" alt="grafik.png" />

**Comment by Tuckerle** [comment]
- [ ] Platz für NWK Namen in NWK-Card erhöhen
