### ISSUE TITLE
Session-Timeout ist zur früh

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#194]
**Describe the bug**
Wenn die Applikation zu lange ohne Userinteraktion geöffnet bleibt wird sie unnutzbar.
**To Reproduce**
    - Öffne die Applikation
    - Mache für eine längere Zeit nichts in der Applikation (15-60 Minuten)
    - Die Applikation wirft unbekannte Fehler und funktioniert nicht mehr

**Expected behavior**
Auch nach längerer Zeit (Stunden) sollte die Applikation weiter verwendbar sein, ohne dass die Browser Cookies gelöscht werden müssen

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tuckerle** [comment]
https://git.muenchen.de/ccse/refarch-security/-/wikis/vorgaben/sessionmanagement
