### ISSUE TITLE
Verlagerung von Logik in den Service - Flag für Ladeanimation

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Praktikumsplaner#212]
Nach [adr-006](https://it-at-m.github.io/Praktikumsplaner/documentation/architecture/adr/adr006-kiss-frontend-components.html) wollten wir doch möglichst wenig Logik in die Komponenten packen.

Bei den Ladeanimationen wird aus meiner Sicht dagegen verstoßen. In der Komponente wird das Flag vor dem Aufruf des Calls auf `true` gesetzt und wenn der Call erfolgreich durch ist auf `false`. Dies sollte aus meiner Sicht aber in den Service verlagert werden da es kein komponentenspezifisches Verhalten ist. In der Komponente sollte nur das Bindung auf die Variable erfolgen.

**Comment by Tuckerle** [comment]
Stand 23.02.24:
Es soll zunächst mit festgelegtem Aufwand ein Prototyp erarbeitet werden, sollte das nicht erfolgreich sein, muss noch einmal gesondert Zeit in die Planung/Konzeption investiert werden.
