### ISSUE TITLE
Löschung von Meldezeiträumen

### ISSUE THREAD

**Issue by LuisEinig** [it-at-m/Praktikumsplaner#217]
**User Story:**  
Als örtliche Ausbildungsleitung möchte ich Meldezeiträume löschen, damit ich Fehler in der benennen und/oder im Zeitraum beheben kann.  

**Akzeptanzkriterien:**  
- [x] es gibt in der Übersicht einen delete button neben jedem Meldezeitraum
- [x] es wird ein Bestätigungsdialog geöffnet
- [x] der Meldezeitraum wird entfernt
- [x] alle zum Meldezeitraum zugehörigen Praktikumsplätze werden gelöscht

**Zusätzliches Infos :**
als high eingestuft, da ein Fehlerhafter Meldezeitraum nur per Datenbank request gelöscht werden kann, und ein nicht Erstellen des richtigen Meldezeitraums verhindert und somit die Arbeit stoppt.

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [ ] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by danielnwz** [comment]
Dieses Issue wurde auf Grund von zeitlichen Engpässen nicht in einem Usabilty-Test getestet. Zählt für uns jedoch trotzdem als abgeschlossen.
