### ISSUE TITLE
Export der Zuweisungstabelle

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#22]
Ich als örtl. Ausbildungsleitung möchte die Zuteilungen in Form einer Tabelle exportieren können, sodass ich diese Tabelle dann ans POR übermitteln kann.

**Akzeptanzkriterien:**
- [x] Zuweisungen werden in eine Tabelle exportiert
- [x] Tabelle wird automatisch auf das Endgerät geladen

Fragen für Refinement:
- [x] Soll es für jede NWK eine extra Warnung geben oder eine Warnung mit einer Liste alle NWKs?
- [x] Eine Warnung für alle Probleme oder für jede Kategorie eine Warnung?
- [x] Soll die Warnung erst bestätigt werden oder trotzdem direkt durchgeführt werden?

Zusätzliche Infos zur Implementierung:

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Unittest gepflegt
- [x] Dokumentation ist gepflegt
- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by MoonaLiisaa** [comment]
Refinement:
- Es soll für jede NWK eine eigene Warnung erscheinen
- Kategorie ist nicht notwendig, da es keine Liste für alle NWK geben soll
- Die Warnung soll erst bestätigt werden und erst dann der Export durchgeführt

**Comment by MoonaLiisaa** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVhsQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b24968b4940dca9dab26913055fdcdd788b96ed4/1741_219_1.5.png)

Infos zur Form der Exportierten Exceltabelle:
Die Form sollte ähnlich zu der Zuweisungstabelle sein die PO jetzt händisch in Excel eintragen und ans POR schicken da das POR dort alle Rückmeldungen auch aus anderen Referanten noch einträgt. Zusätzlich Spalte namentliche Anforderungen ist natürlich kein Problem

**Comment by MoonaLiisaa** [comment]
Update:
es wurde folgendes Akzeptanzkriterium rausgenommen: 
"Es wird eine Warnung angezeigt, wenn beim Export NWKs schon mal bei der Stelle waren"

DoTo: neue Story schreiben @danielnwz 

Wichtig: In Zukunft muss die Verbindung zu dieser Story weiterhin gewährleistet wird.

**Comment by Tuckerle** [comment]
- [ ] GetEndpoint erstellen
- [ ] ExcelExportservice erstellen
- [ ] Design vorhanden
- [ ] design implementieren
- [ ] excel automatisch speichern (Standardpeicherort von Browser, wenn möglich, ansonsten Downloads(?))
