### ISSUE TITLE
UpdateNwkDialog anpassen

### ISSUE THREAD

**Issue by IamPekka058** [it-at-m/Praktikumsplaner#220]
Das Layout des UpdateNwkDialogs soll dem Aussehen des CreateNwkDialog angepasst werden.

- [x] Eingabe des Namens in einer Zeile mit zwei Spalten (wie beim NwkCreateDialog)
- [x] Möglichkeit zur Veränderung der Vorlesungstage

Definition of Done (DoD)

- [x] Dialog passt visuell besser zum Layout von NwkCreateDialog
- [x] Erfüllt Akzeptanzkriterien

**Comment by IamPekka058** [comment]
Das Layout des UpdateNwkDialogs soll dem Aussehen des CreateNwkDialog angepasst werden.

- [ ] Eingabe des Namens in einer Zeile mit zwei Spalten

Definition of Done (DoD)
- [ ] Dialog passt visuell besser zu Layout von NwkCreateDialog

**Comment by Tuckerle** [comment]
in #216 mit umgesetzt während Vue3 bedingte Probleme in diesem Dialog gefixt wurden
