### ISSUE TITLE
Ungültiges Pflichtfeld der Ausbildungsmeldung

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#226]
**Describe the bug**
Beim Melden einer Praktikumsstelle für Auszubildende ist die Information zum Feld "Programmierkenntnisse" ein Pflichtfeld und auch so als dieses gekennzeichnet, obwohl dies keins sein sollte. 

**To Reproduce**
   - Gehe auf 'Praktikumsplätze' 
   - Klicke auf 'hinzufügen'
   - Klicke auf 'Ausbildung'
   - Das Feld Programmierkenntnisse ist ein Pflichtfeld

**Expected behavior**
Es sollte kein Pflichtfeld mehr sein.

**Comment by Tuckerle** [comment]
Als Lösungsansatz wurde sich hier darauf geeinigt, dass alle Komponenten die in der Meldung Daten abfragen eine property "required" bekommen, anhand der entschieden wird  wie die Komponenten aussehen und sich verhalten.
Hierzu soll nicht im template mit v-if gearbeitet werden sondern mit Konstanten (oder wenn nicht anders machbar) Variablen im <script> um das Aussehen und Verhalten zu beeinflussen.
