### ISSUE TITLE
Mail-Versand: erfolgreiche Praktikumszuteilung Ausbilder*innen

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#24]
Ich als örtl. Ausbildungsleitung möchte die Info-Mails an die örtl. Ausbilder*innen automatisiert verschicken lassen, sodass ich nicht > 100 Mails selbstständig verschicken muss.

**Akzeptanzkriterien:**
- [x] Es wird der genaue Zuweisungszeitraum der jeweiligen Studiengruppen abgefragt
- [x] Mail-Vorlage wird mit korrekten Daten befüllt
- [x] Mail wird nach Bestätigung durch mich versendet
- [x] ein Feedback wird zurückgegeben ob die Mails erfolgreich versendet wurden

Zusätzliche Infos zur Implementierung:
Aufbau des Mail wird noch geklärt

Fragen für das Refinement:
- [x] Aufbau benötigte Daten PDF
- [x] Datenbeschaffung (Wie kommen wir an die benötigten Daten?)

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Unittest gepflegt
- [x] Dokumentation ist gepflegt
- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by MoonaLiisaa** [comment]
Update:
es wurde folgendes Akzeptanzkriterium rausgenommen:
"Es wird eine Warnung angezeigt, wenn beim Export NWKs schon mal bei der Stelle waren"

DoTo: neue Story schreiben @danielnwz

Wichtig: In Zukunft muss die Verbindung zu dieser Story weiterhin gewährleistet wird.

**Comment by danielnwz** [comment]
ToDo: Wandert in eigene Story: "PDF ist der Mail angehängt" @danielnwz

**Comment by Tuckerle** [comment]
- [ ] Klärung technischer User
- [ ] MailService Erstellen
- [ ] Mailvorlage erstellen (wie wir die Backendseitig umgesetzt)
- [ ] Mail Anbindung Konfiguration (Umgebungsvariablen/OpenShift Secrets)
- [ ] Eingabeoption für die Zuweisungszeiträume der Fachrichtungen (v.a. BSC & VI)
- [ ] Bestätigungsfenster, ob alle eingaben korrekt sind und die Mails verschickt werden sollen
  - [ ] Zuweisungszeiträume zur Prüfung anzeigen
  - [ ] Bestätigung einholen
- [ ] Fehler bei Mailversand sammeln 
  - [ ] Fehler an User zurückgeben
