### ISSUE TITLE
V-select schließt sich nicht nach einem Klick auf anderes Element

### ISSUE THREAD

**Issue by IamPekka058** [it-at-m/Praktikumsplaner#246]
Describe the bug
Bei manchen v-select Komponenten gibt es template items (zb "Alle" bei der Studiensemesterauswahl) Wenn man dieses template item klickt und danach eine andere v-select Komponente anklickt schließt sich der v-select nicht.

To Reproduce

    Go to 'Praktikumsplätze'
    Open a form to create a Stelle (either Studiumspraktikumsplatz or Ausbildungspraktikumsplatz)
    Click one v-select with template item (e.g. Studiensemesterselect/Ausbildungsjahrselect)
    Click another v-select
    See error

Expected behavior
Der zuerst geöffnete v-select sollte geschlossen werden
Screenshots<img width="1457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3lZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bdcc40de935e93fc49ab3b717ab4cf88648db432/04f45af8-c583-4c59-a183-02d5d1a2a2b0.PNG" alt="04f45af8-c583-4c59-a183-02d5d1a2a2b0.PNG" />

**Comment by danielnwz** [comment]
Bug tritt nicht mehr auf. Issue wird geschlossen.
