### ISSUE TITLE
Erstellung eines Meldezeitraums

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#31]
Als örtl. Ausbildungsleitung möchte ich einen Meldezeitraum einrichten können, sodass die örtl. Ausbilder*innen in diesem Zeitraum Praktikumsplätze melden können.

**Akzeptanzkriterien:**
- [x] Zeitraum kann erstellt werden
- [x] Es wird überprüft, sodass die Startzeit nicht nach der Endzeit ist

Zusätzliche Infos zur Implementierung:
- Zeitraum hat einen Titel
- Start-/Endzeitpunkt für die Meldung

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Unittest gepflegt
- [x] Dokumentation ist gepflegt
- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by MoonaLiisaa** [comment]
- [ ] Design erstellen
- [ ] Backend Endpoint erstellen (DTO)
- [ ] Datenstruktur erstellen (Datenbank)
- [ ] Testaufgaben erstellen (für Usability Tests)
- [ ] Frontendverbindung zum Backend ist vorhanden
- [ ] Frontendvalidierungen erstellen
- [ ] Backendvalidierungen erstellen
- [ ] Frontendoberfläche implementieren

**Comment by TobiasCersowsky** [comment]
https://www.figma.com/file/ONO0rluJLepS9T3DvfXlUV/Erstellung-eines-Meldezeitraums%2331?type=design&node-id=0%3A1&mode=design&t=ePv89k53cP6oOwQF-1
