### ISSUE TITLE
Details Praktikumsstelle Zuweisung

### ISSUE THREAD

**Issue by LuisEinig** [it-at-m/Praktikumsplaner#39]
Als örtl. Ausbildungsleitung möchte ich auf der Zuweisungsseite schnell alle vorhandenen Informationen zu einer Praktikumsstelle erhalten können, sodass ich diese bei der Zuweisung berücksichtigen kann.

**Akzeptanzkriterien**

- [x] Alle Informationen zu einer Praktikumsstelle sind in der Zuweisung ersichtlich

Fragen für Refinement:
- [x] Welche Informationen sind das?
- [x] Gibt es schon einen Plan auf welche art die Details dargestellt werden sollen
  - [x] Dialog, Hover, "Cardexpansion " etc.

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Unittest gepflegt
- [x] Dokumentation ist gepflegt
- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by Tuckerle** [comment]
Refinment:
Ausbilder, Dringlichkeit & Aufgaben sollen angezeigt werden
