### ISSUE TITLE
Praktikumsplätze Erstellen

### ISSUE THREAD

**Issue by LuisEinig** [it-at-m/Praktikumsplaner#40]
Als örtl. Ausbildungsleitung möchte ich Praktikumsplätze auch außerhalb der Meldezeiträume erstellen können, sodass ich mehr NWKs Zuweisen kann.

**Akzeptanzkriterien**

- [x] Es gibt eine Funktion einen Praktikumsplatz zu erstellen
- [x] Es ist möglich ihn außerhalb eines Meldezeitraumes zu erstellen
- [x] Es werden die gleichen Daten wie bei der Meldung abgefragt

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [ ] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Unittest gepflegt
- [x] Dokumentation ist gepflegt
- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by danielnwz** [comment]
Wurde bereits durch Issue [#130](https://app.zenhub.com/workspaces/praktikumsplaner-650bff5c552a4616fb4b3a8d/issues/gh/it-at-m/praktikumsplaner/130) umgesetzt.
