### ISSUE TITLE
Definition of Ready 

### ISSUE THREAD

**Issue by MoonaLiisaa** [it-at-m/Praktikumsplaner#43]
Template für Definition of Ready erstellen.

Dieses soll folgende Punkte beinhalten:
- Story ist aus der Sicht der Persona geschrieben
- Akzeptanzkriterien sind vorhanden
- Das Issue wurde geschätzt

**Comment by danielnwz** [comment]
Erster Entwurf:

**Definition of Ready (DoR):**

- [ ] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [ ] Vollständige und klare Akzeptanzkriterien sind definiert.
- [ ] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

**Comment by danielnwz** [comment]
DoR wurde den bereits erstellten Issues hinzugefügt.

**Comment by LuisEinig** [comment]
PR wurde gemerged
