### ISSUE TITLE
join the it@M open source club - Logo finden

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Praktikumsplaner#63]
OpenSource Software von it@M wird aktuell hier gelistet: https://it-at-m.github.io/opensource.muenchen.de/de/publish.html

Wir sollten versuchen dort auch gelistet zu werden. Dazu ist es aus meiner Sicht notwendig dass wir ein schönes Logo für unser Projekt haben. Das sollte dann das Logo in der [Doku](https://it-at-m.github.io/Praktikumsplaner/) ersetzen, sowie als Avatar in Github nutzbar sein und eben auch in der Liste auftauchen.

@it-at-m/praktikumsplaner_devs

**Comment by MoonaLiisaa** [comment]
Aktueller Stand: sollte am Projektende stehen
Muss noch als User Story formuliert werden.

**Comment by danielnwz** [comment]
User Story wurde formuliert: #151
