### ISSUE TITLE
Technical: Verwendung von Flyway

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Praktikumsplaner#64]
Das Datenbankschema soll mittels Flyway versioniert werden. Die Verisonierung soll mindestens für PostgreSQL erfolgen. H2-Support ist aus meiner Sicht optional.

**Comment by MoonaLiisaa** [comment]
- [ ] Flywayabhängigkeit einbinden
- [ ] Konfigurationsdateien (YAML) für Flyway anpassen
- [ ] Skript erstellen für bestehende Entitys of D
- [ ]
