### ISSUE TITLE
DB-Tabellen sind nicht vorhanden

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Praktikumsplaner#68]
**Describe the bug**
Wenn die Anwendung in einer Container-Plattform läuft sind die DB-Tabellen nach Abschluss des Deployments nicht mehr vorhanden.

Ursache hierfür ist vermutlich das die Tabellen beim Herunterfahren eines Pods die Tabellen gelöscht werden. Wenn es nur einen Pod gibt wird zuerst der neue Pod erstellt. Läuft dieser erfolgreich wird der alte Pod gestoppt und somit werden die Tabellen gelöscht.

Hier ein Auszug aus dem Log bei der lokalen Ausführung:

```
2023-10-17T12:05:17.243+02:00  INFO 16904 --- [ionShutdownHook] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
Hibernate: 
    
    drop table if exists NWK cascade 
Hibernate: 
    
    drop table if exists TheEntity cascade 
2023-10-17T12:05:17.449+02:00  INFO 16904 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2023-10-17T12:05:17.460+02:00  INFO 16904 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

**To Reproduce**
- OpenShift Infrastructur mit Rolling Deployment, einem Pod und einer externen DB
- Start ein neues Deployment an
- wenn das Deployment durch ist kann man in der DB sehen dass die Tabelle weg ist

**Expected behavior**
Ziel sollte sein das die Tabelle weiterhin vorhanden ist und so die Anwendung genutzt werden kann, wenn ein Rolling Deployment stattfindet. Steht wahrscheinlich im Verbindung mit #64

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIN7
 - Browser: FF
 - Version: 102

**Smartphone (please complete the following information):**
nicht verwendet

**Additional context**

**Comment by MrSebastian** [comment]
Hotfix: den neuen Pod neustarten. Danach sollten die Tabellen wieder vorhanden sein.

**Comment by Tuckerle** [comment]
- [ ] Versuchen Bug über DDL-AUTO property zu beheben
- [ ] Wenn nicht gelungen:
  - [ ] Bug weiter analysieren
  - [ ] Bug beheben

**Comment by Tuckerle** [comment]
Grundsätzlich lässt sich der Bug beheben, indem die Konfigurationsdatei wie oben beschrieben angepasst werden. Durch die Einbindung von Flyway für die Dantbankmigration ist das auch schon umgesetzt.
Die Frage die sich jetzt noch stellt ist, wie verfahren wir mit den bisherigen Tabellen auf DEV und TEST, lassen wir die so bestehen wie sie sind und benennen die flyway_migration tabelle um oder löschen wir alle Tabellen die es aktuell gibt? @MrSebastian 

Auf DEV habe ich zum Testen die Tabelle umbenannt, TEST habe ich bisher in Ruhe gelassen.

**Comment by MrSebastian** [comment]
Ich würde die alten Daten (Tabellen) löschen
