### ISSUE TITLE
Securitykonzept beschreiben und umsetzen

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Praktikumsplaner#69]
- es muss beschrieben werden wie die Zugriffsbeschränkung mit Spring-Security erfolgt (z.b. Rollen oder Rechte)
- wichtig ist, das klar ist welche Persona was darf
 
# Akzeptanzkriterien
- [x] bisherige Funktionalität muss angepasst werden
- [x] der lokalen Stack muss entsprechend angepasst werden
- [x] das Konzept muss in der Doku hinterlegt sein

**Comment by LuisEinig** [comment]
- [ ] Auswahl ob Rollen oder Rechte
- [ ] Berechtigung für Personas Ermitteln
- [ ] Berechtigung Setzen
   - [ ] anpassung von lokalen stack und sso dev
- [ ] Frontend Autorisierungsprüfung im Code
 - [ ] Bei fehlender Berechtigung soll eine [undefiniertes UI element] angezeigt werden mit option auf redirect zurück zu Berechtigtem Bereich
- [ ] Backend Autorisierungsprüfung im Code
  - [ ] Rückgabe von 403 HTTP Codes
- [ ] Berechtigungen Dokumentieren
- [ ] Technische Umsetzung Dokumentieren
