### ISSUE TITLE
Praktikumsstellen Meldung örtl. Ausbilder*innen

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#7]
Ich als örtliche Ausbilder*in möchte die von mir angebotenen Praktikumsstellen melden können, sodass die örtlichen Ausbildungsleitungen einen guten Überblick über meine Stellen haben. 

**Akzeptanzkriterien:**
- [x] Hierzu werden alle Daten abgefragt, die für eine Praktikumsstelle relevant sind
- [x] Es ist klar ersichtlich, welche Angaben Pflichtangaben sind
- [x] Es gibt ein Feedback, ob meine Meldung erfolgreich war
- [x] Voraussichtlicher Zuweisungszeitraum der NWK wird bei Auswahl von Studien- und Jahrgang angezeigt

Zusätzliche Infos zur Implementierung:
Angaben: 
- Referat: ITM/RIT 
- konkrete Dienststelle (PFLICHTFELD)
- örtliche Ausbilder*in (PFLICHTFELD)
- Kontaktdaten (Mail) (PFLICHTFELD)
- Aufgaben am Praktikumsplatz -> Freitextfeld (PFLICHTFELD)
- Dringlichkeit: Zwingend/Dringend/Nachrangig (PFLICHTFELD)
- Namentliche Anforderung: Optional, wenn gewisse NWK gefordert wird

- Ausbildungstyp: Ausbildung/ Studium 

- Projektarbeit (Pflichtfeld bei Ausbildung): Ja/Nein
- Ausbildungsjahr (Pflichtfeld bei Ausbildung): 1.Jahr/2.Jahr/3.Jahr/Egal 
- Ausbildungsrichtung: Auswahl der versch. Ausbildungsrichtungen (Pflichtfeld bei Ausbildung)

- Programmierkenntnisse (Pflichfeld bei Studium): Ja/Nein
- Studiensemester (Pflichtfeld bei Studium): 1.Semester/2.Semester/3.Semester/4-5.Semester(Praxissemester)/6.Semester
- Studienart: Auswahl der versch. Studiengänge (Pflichtfeld bei Studium) 

Bei Auswahl der Ausbildungs/Studienart soll der Zeitraum, in der die NWKs kommen, dazu geschrieben sein.

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [x] Unittest gepflegt
- [x] Dokumentation ist gepflegt
- [x] Usability Test wurden durchgeführt
- [x] Auf Testumgebung verfügbar
- [x] Akzeptanzkriterien sind alle erfüllt

**Comment by MoonaLiisaa** [comment]
- [ ] Design erstellen
- [ ] Backend Endpoint erstellen (DTO)
- [ ] Datenstruktur erstellen (Datenbank)
- [ ] Testaufgaben erstellen (für Usability Tests)
- [ ] Frontendverbindung zum Backend ist vorhanden
- [ ] Frontendvalidierungen erstellen
- [ ] Backendvalidierungen erstellen
- [ ] Frontendoberfläche gem. Design implementieren
- [ ] Berechnung von voraussichtlichen Zuweisungszeitraum

**Comment by TobiasCersowsky** [comment]
Link zu Figma: https://www.figma.com/file/S6Fwynn99EbCitJYIjxpHB/Praktikumsstellen-Meldung-%C3%B6rtl.-Ausbilder*innen%237?type=design&mode=design&t=F01YzldpqRW554qT-1
