### ISSUE TITLE
Angabe zur Verfügbarkeit einer Planstelle

### ISSUE THREAD

**Issue by Tuckerle** [it-at-m/Praktikumsplaner#79]
**User Story:**  
Ich als örtliche Ausbildungsleitung möchte, dass die örtlichen Ausbilder*innen bei der Meldung von Praktikumsstellen angeben können ob in ihrem Team eine Planstelle verfügbar wäre, so dass ich bei der Zuweisung NWKs die demnächst fertig werden mit der Ausbildung vorrangig auf diese Stellen verplanen kann, um eine sinnvolle Übernahme zu gewährleisten.

**Akzeptanzkriterien:**  
- [x] In der Meldemaske für Ausbildungsstellen gibt es ein Feld zum angeben ob eine Planstelle existiert
- [x] In der Zuweisungsübersicht sind Praktikumsstellen welche auch eine Planstelle haben zusätzlich markiert

**Zusätzliches Infos zur Implementierung:**
Nachdem es nicht explizit als Pflichtfeld in der Story steht wird es zunächst als optional behandelt.

---
**Definition of Ready (DoR):**

- [x] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [x] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [ ] Akzeptanzkriterien sind alle erfüllt

**Comment by MoonaLiisaa** [comment]
**Wichtig:** Hier liegt eine Abhängigkeit zu Issue #8 vor.

**Comment by Tuckerle** [comment]
- [ ] DTOs anpassen
- [ ] Datenmodell anpassen (Datenbank)
- [ ] Design vorhanden
- [ ] Design implementieren
- [ ] POST-Request im Frontend anpassen
