### ISSUE TITLE
Praktikumsstellen Meldung örtl. Ausbildungsleitung

### ISSUE THREAD

**Issue by danielnwz** [it-at-m/Praktikumsplaner#8]
Als örtliche Ausbildungsleitung möchte ich angebotene Praktikumsstellen eintragen können, nachdem ich diese Stellenangebote mit den örtl. Ausbilder*innen auf anderem Wege abgesprochen habe.

**Akzeptanzkriterien:**
- [x] Hierzu werden alle Daten abgefragt, die für eine Praktikumsstelle relevant sind
- [x] Es ist klar ersichtlich, welche Angaben Pflichtangaben sind
- [x] Es gibt ein Feedback ob meine Meldung erfolgreich war
- [x] Voraussichtlicher Zuweisungszeitraum der NWK wird bei Auswahl von Studien- und Jahrgang angezeigt

Zusätzliche Infos zur Implementierung:
Angaben: 
- Referat: ITM/RIT 
- konkrete Dienststelle (PFLICHTFELD)
- örtliche Ausbilder*in (PFLICHTFELD)
- Kontaktdaten (Mail) (PFLICHTFELD)
- Aufgaben am Praktikumsplatz -> Freitextfeld (PFLICHTFELD)
- Dringlichkeit: Zwingend/Dringend/Nachrangig (PFLICHTFELD)
- Namentliche Anforderung: Optional, wenn gewisse NWK gefordert wird

- Ausbildungstyp: Ausbildung/ Studium 

- Projektarbeit (Pflichtfeld bei Ausbildung): Ja/Nein
- Ausbildungsjahr (Pflichtfeld bei Ausbildung): 1.Jahr/2.Jahr/3.Jahr/Egal 
- Ausbildungsrichtung: Auswahl der versch. Ausbildungsrichtungen (Pflichtfeld bei Ausbildung)

- Programmierkenntnisse (Pflichfeld bei Studium): Ja/Nein
- Studiensemester (Pflichtfeld bei Studium): 1.Semester/2.Semester/3.Semester/4-5.Semester(Praxissemester)/6.Semester
- Studienart: Auswahl der versch. Studiengänge (Pflichtfeld bei Studium) 

Bei Auswahl der Ausbildungs/Studienart soll der Zeitraum, in der die NWKs kommen, dazu geschrieben sein.

Fragen für Refinement:
- [x] Pflichtfelder nochmal genauer spezifizieren, vor allem was "bei Ausbildung/Studium" bedeutet
- [x] Braucht ihr alle Felder wie die Ausbilder*innen oder könnten bestimmte Daten mit Standardwerten gefüllt werden?
  - [x] z.b. Namentliche Anforderung immer leer

- [ ] Meldet ihr auch Stellen, nachdem der Meldezeitraum eigentlich schon abgelaufen ist?
---
**Definition of Ready (DoR):**

- [ ] Die User Story ist klar und verständlich aus der Perspektive der betroffenen Persona formuliert.
- [x] Vollständige und klare Akzeptanzkriterien sind definiert.
- [ ] Die Aufwandsschätzung für das Issue wurde durchgeführt und dokumentiert.

---
**Definition of Done (DoD):**

- [ ] Unittest gepflegt
- [ ] Dokumentation ist gepflegt
- [ ] Usability Test wurden durchgeführt
- [ ] Auf Testumgebung verfügbar
- [ ] Akzeptanzkriterien sind alle erfüllt

**Comment by MoonaLiisaa** [comment]
Update: aus dem 2. Sprint Planning ist herausgegangen, dass das Issue #7 nicht ganz eindeutig und klar formuliert wurde. Aus diesem Grund muss auch dieses Issue nochmal angeschaut werden und auf Verständlichkeit und Vollständigkeit geprüft werden.

**Comment by TobiasCersowsky** [comment]
https://www.figma.com/file/fuNTKC9OZJM01CfRxyO4Md/PraktikumsstellenMeldung-%C3%B6rtl.-Ausbildungsleitung%238?type=design&node-id=36%3A4089&mode=design&t=Bm9qdV0vIbyDvSD4-1

**Comment by andingerMUC** [comment]
Refinement:
    Referat: ITM/RIT
    konkrete Dienststelle (PFLICHTFELD)
    örtliche Ausbilder*in (PFLICHTFELD)
    Kontaktdaten (Mail) (PFLICHTFELD)
    Aufgaben am Praktikumsplatz -> Freitextfeld (PFLICHTFELD)
    Dringlichkeit: Zwingend/Dringend/Nachrangig (PFLICHTFELD)
    Namentliche Anforderung: Optional, wenn gewisse NWK gefordert wird
    Ausbildungstyp: Ausbildung/ Studium (PFLICHTFELD) wird anfangs abgefragt
    Projektarbeit (Pflichtfeld bei Ausbildung): Ja/Nein (wird nicht bei Studis angezeigt)
    Ausbildungsjahr (Pflichtfeld bei Ausbildung): 1.Jahr/2.Jahr/3.Jahr/Egal (Mehrfachauswahl erwünscht vom PO)
    Ausbildungsrichtung: Auswahl der versch. Ausbildungsrichtungen (Pflichtfeld bei Ausbildung) (wird nicht bei Studis angezeigt)
    Programmierkenntnisse (Pflichfeld bei Studium; bei Ausbildung optional): Ja/Nein
    Studiensemester (Pflichtfeld bei Studium): 1.Semester/2.Semester/3.Semester/4-5.Semester(Praxissemester)/6.Semester  (Mehrfachauswahl erwünscht vom PO) (wird nicht bei Azubis angezeigt)
    Studienart: Auswahl der versch. Studiengänge (Pflichtfeld bei Studium)(wird nicht bei Azubis angezeigt)

Es werden alle Felder benötigt wie bei der normalen Meldung. 

Feld Projektarbeit:  war bei Usability Tests nicht eindeutig genug für Tester; es wird ein Infotext benötigt! Hintergrund: jeder Azubi benötigt im letzten Jahr eine Projektarbeit für sich; 75 Wochenstunden; ist die Abschlussarbeit

Muss noch auf normale Meldung übertragen werden!

**Comment by MoonaLiisaa** [comment]
**Wichtig:** Hier liegt eine Abhängigkeit zu Issue #79 vor.

**Comment by MoonaLiisaa** [comment]
Diese Story muss überarbeitet werden, da aus dem Refinement neue Überarbeitungen hinzugekommen sind. Felder sind bereits in der Anwendung implementiert und müssen auch im Issue #13 ("normale Meldung") mit angepasst werden. 
ToDo: Es wird eine neue User Story geschrieben. @danielnwz

**Comment by danielnwz** [comment]
Story könnte aus meiner Sicht so vom PO abgenommen werden, da die Verbesserungen für die Meldung in Issue #129 und #130 behandelt werden und die Meldung für die Ausbildungsleitung so bereits möglich ist.
